### ISSUE TITLE
Fintechee FIX API Installation Key

### ISSUE THREAD

**Issue by jordigh81** [fintechees/FIX-API-Pro#1]
Hello,

I don't know where to include the key for the API installation. Can someone tell me where to add the key to install the application?

Thank you very much and best regards,

**Comment by fintechee** [comment]
@ jordigh81

Hi, first of all, thank you for using our FIX API trading platform individual version.
So, you didn't have a file named "util.cfg" under the root directory?

**Comment by jordigh81** [comment]
Hello, Thank you for your reply. No, I don't have any file with that name.

**Comment by fintechee** [comment]
@jordigh81
Oh, really?
It's very important to have this file. It will do initial configuration when you start the FIX API trading platform.
I will publish this file's template here.

**Comment by jordigh81** [comment]
When I run fixpro-6.0.jar, only a file named cclogfile.log appears, and the campaign file that was in the downloaded zipped folder. I also included the json folder.

**Comment by fintechee** [comment]
No worries. I have sent somebody create a template. It will be published soon.

**Comment by fintechee** [comment]
@ jordigh81

Please check util.cfg under the root directory.
Usually you just need to set SenderCompID, EMail, LicenseKey and keep other settings as the default values.

**Comment by jordigh81** [comment]
> @ jordigh81
> 
> Please check util.cfg under the root directory.
> Usually you just need to set SenderCompID, EMail, LicenseKey and keep other settings as the default values.

Thanks for the help, but the problem persists. The error is:

"Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'RC': Unsatisfied dependency expressed through field 'util'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'util' defined in URL [jar:file:/C:/Users/jordi/AppData/Local/Programs/FIX-API-Pro-main/fixpro-6.0.jar!/BOOT-INF/classes!/com/channelsea/fixpro/util/Util.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.channelsea.fixpro.util.Util]: Constructor threw exception; nested exception is java.lang.NullPointerException: inStream parameter is null"

**Comment by fintechee** [comment]
Oh, you are using windows......
The setting(the folder's structure) would be a little bit different from ubuntu......
Unfortunately, because I never use windows anymore, so I can't reproduce this error.
Can you change the OS to linux and then try again?
